# dev 环境
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/${db_ame}?serverTimezone=UTC
    username: ${username}
    password: ${password}

server:
  port: 8082